uploads = []
generated = []

[[outputs]]
id = "7pbmdWxKppRMfpu4kK-rn"
uri = "file://deploy/akoya-properties-deploy.tar.gz"
type = "unspecified"
title = "Akoya Properties — Deploy Bundle v1.0.3 (.tar.gz, 37 MB)"

[[outputs]]
id = "PeQih_On3SC39fAvhOY7t"
uri = "file://deploy/akoya-properties/README-DEPLOY.txt"
type = "text"
title = "Deployment Instructions"

[[outputs]]
id = "tQtoMwyZqQ7QRRjMT9OL3"
uri = "file://deploy/akoya-properties-deploy.zip"
type = "unspecified"
title = "Akoya Properties — Deploy Bundle v1.0.3 (.zip, 37 MB)"
